
modLoader="javafml" #mandatory
loaderVersion="[43,)"
license="MIT License"
[[mods]]
modId="gearbox"
version="${file.jarVersion}"
displayName="Gearbox"
credits="simibubi, oierbravo, & latvian dev"
authors="Redz aka terentre4e25caracteres" #optional
description='''
Mod made for use in Create: Back on Track modpack
'''
[[dependencies.gearbox]]
modId="forge"
mandatory=true
versionRange="[43,)"
ordering="NONE"
side="BOTH"
[[dependencies.gearbox]]
modId="minecraft"
mandatory=true
versionRange="[1.19.2,1.20)"
ordering="NONE"
side="BOTH"
[[dependencies.gearbox]]
    modId="create"
    mandatory=true
    versionRange="[0.5.1.f,)"
    ordering="NONE"
    side="BOTH"
